"""Search taxonomy for SciLitAI arXiv ingestion."""

from __future__ import annotations

TARGET_CATEGORIES: tuple[str, ...] = (
    "cs.LG",
    "stat.ML",
    "physics.comp-ph",
    "physics.flu-dyn",
    "cond-mat.soft",
    "math.NA",
    "eess.SY",
    "cs.SE",
    "cs.DC",
)

CLUSTER_WEIGHTS: dict[str, float] = {
    "sciml_pinns": 5.0,
    "neural_operators_rom_surrogates": 4.0,
    "cfd_rheology_fem_generative_flow": 2.0,
    "industry40_uns_predictive_maintenance": 1.0,
    "uq_probabilistic_methods": 1.0,
}

SEARCH_CLUSTERS: dict[str, tuple[str, ...]] = {
    "sciml_pinns": (
        "Scientific Machine Learning",
        "SciML",
        "Physics-Informed",
        "PINN",
        "PINNs",
        "Structure-Preserving",
        "Hamiltonian Neural Networks",
        "Lagrangian Neural Networks",
        "Universal Differential Equations",
        "UDE",
        "Neural ODE",
        "Collocation Methods",
        "Meshfree Neural",
    ),
    "neural_operators_rom_surrogates": (
        "Neural Operator",
        "FNO",
        "Fourier Neural Operator",
        "DeepONet",
        "Wavelet Neural Operator",
        "WNO",
        "GNO",
        "GINO",
        "Surrogate Modeling",
        "Model Order Reduction",
        "ROM",
        "POD",
        "DMD",
        "SVD",
        "Nonlinear ROM",
        "SINDy",
        "Gaussian Process Regression",
        "GPR",
    ),
    "uq_probabilistic_methods": (
        "Uncertainty Quantification",
        "UQ",
        "Bayesian Neural Networks",
        "BNN",
        "Bayesian Optimization",
        "MCMC",
        "Gaussian Process",
        "Conformal Prediction",
        "Sensitivity Analysis",
        "Epistemic Uncertainty",
        "Aleatoric Uncertainty",
    ),
    "cfd_rheology_fem_generative_flow": (
        "Computational Fluid Dynamics",
        "CFD",
        "Turbulence Modeling",
        "RANS",
        "LES",
        "DNS",
        "Flow Reconstruction",
        "Flow Super-Resolution",
        "Aerodynamic Drag",
        "Fluid-Structure Interaction",
        "Heat Transfer",
        "Rheology",
        "Non-Newtonian Fluid",
        "Polymer Processing",
        "Rubber Processing",
        "Vulcanization",
        "Finite Element",
        "FEM",
        "FEA",
        "Structural Dynamics",
        "Mechanical Vibrations",
        "Generative Flow Modeling",
        "Physics-Informed GAN",
        "Diffusion Models",
    ),
    "industry40_uns_predictive_maintenance": (
        "Digital Twin",
        "Predictive Maintenance",
        "Fault Detection",
        "Remaining Useful Life",
        "RUL",
        "Unified Namespace",
        "UNS",
        "Industrial Data Architecture",
        "Industrial Data Lake",
        "OT/IT Convergence",
        "IIoT",
        "Event-Driven Architecture",
        "MQTT",
        "Sparkplug B",
        "OPC UA",
        "Smart Manufacturing",
    ),
}
